# Generated by Django 4.2.8 on 2023-12-05 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hypergen_translation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translation',
            name='status',
        ),
    ]
