# Generated by Django 4.2.8 on 2023-12-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypergen_translation', '0002_remove_translation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='value',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
