# Generated by Django 4.2.8 on 2023-12-05 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hypergen_translation', '0003_translation_value'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TranslationStatus',
        ),
    ]
