# Generated by Django 4.2.8 on 2023-12-08 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hypergen_translation', '0005_alter_translation_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='string',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hypergen_translation.string'),
        ),
    ]
